spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://129.28.162.63:3306/adminV1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root1234
      dbType: mysql   # 指定数据库类型 mysql
      initialSize: 5  # 启动初始化连接数量
      minIdle: 5      # 最小空闲连接
      maxActive: 20   # 最大连接数量（包含使用中的和空闲的）
      maxWait: 60000  # 最大连接等待时间 ，超出时间报错
      timeBetweenEvictionRunsMillis: 60000  #  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   #   # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 1         # 验证连接有效性的sql, SELECT 1 FROM DUAL是oracle的在验证语句
      testWhileIdle: true             # 空闲时校验
      testOnBorrow: false  # 使用中是否校验有效性
      testOnReturn: false  # 归还连接池时是否校验
      poolPreparedStatements: false  # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      #max-pool-prepared-statement-per-connection-size: 20 #开启上边时语句时配置

      stat-view-servlet:
        enabled: true
        reset-enable: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
  redis:
    database: 0
    host: 129.28.162.63
    port: 6379
    password: redis1234
    timeout: 10000 #连接超时时间
    jedis:
      pool:
        max-wait: -1 #阻塞最大等待时间 负值表示五限制
        max-active: 100 #最大活动连接
        max-idle: 10 #最大空闲连接数
        min-idle: 1 #mix 空闲连接数
mybatis:
#  classpath后面的 * 必不可少,，缺少*号的话后面的通配符不起作用。   **表示可以表示任意多级目录。
  # 如果mapper.xml文件放在resources中需要下面这行配置，如果和dao接口放在一个包中不需要
  type-aliases-package: com.rog.adminpermission
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  config: classpath:logback-spring.xml
